name: Deploy Medusa

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.9.5

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve

    - name: SSH into EC2 and Deploy Medusa
      run: |
        ssh -i /path/to/akula_key.pem ubuntu@your-ec2-public-ip << 'EOF'
          # Install Docker
          sudo apt-get update
          sudo apt-get install -y docker.io

          # Start Docker service
          sudo systemctl start docker
          sudo systemctl enable docker

          # Pull Medusa Docker image
          sudo docker pull medusajs/medusa:latest

          # Run Medusa container
          sudo docker run -d --name medusa -p 7001:7001 medusajs/medusa

          # Check Medusa logs
          sudo docker logs medusa
        EOF
